train_model:
  RandomForestRegressor:
    max_depth:
    - 5
    - 8
    - 15
    - 10
    max_features:
    - 5
    - 7
    - 8
    min_samples_split: 
    - 2
    - 8
    - 15 
    - 20
    n_estimators:
    - 100
    - 200
    - 500
  XGBRegressor:
    learning_rate:
    - 0.1
    - 0.01
    max_depth:
    - 5
    - 8
    - 12
    - 20
    n_estimators:
    - 100
    - 200
    - 300
    colsample_bytree:
    - 0.5
    - 0.8
    - 0.3
    - 0.4
base_model_score: '0.1'